### ISSUE TITLE
insufficientFilePermissions error

### ISSUE THREAD

**Issue by xplorer990** [chazlarson/sb_gd#2]
SomeName@SomeMachine:~/sb_gd$ python sb_sd.py
Traceback (most recent call last):
  File "sb_sd.py", line 120, in <module>
    td_id = create_td(drivename)
  File "sb_sd.py", line 68, in create_td
    return DRIVE.teamdrives().create(body=body,
  File "/home/SomeName/sb_gd/sb_gd/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/SomeName/sb_gd/sb_gd/lib/python3.8/site-packages/googleapiclient/http.py", line 937, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/teamdrives?requestId=***&fields=id&alt=json returned "The user does not have sufficient permissions for this file.". Details: "[{'message': 'The user does not have sufficient permissions for this file.', 'domain': 'global', 'reason': 'insufficientFilePermissions'}]">

(Message from HttpError link)

"{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "required",
    "message": "Login Required",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Login Required"
 }
}"

**Comment by chazlarson** [comment]
Is there a recipe to reproduce this?  I can't make this happen with any of four Google accounts on multiple systems.

**Comment by Gotanius** [comment]
I'm getting the same error. I'm following the saltbox instructions. 
The main google account already has a working and in use google drive.

Got the fix. Needed to turn on shared drives in the admin console. Please follow https://support.google.com/a/answer/7337635

**Comment by xplorer990** [comment]
> I'm getting the same error. I'm following the saltbox instructions. The main google account already has a working and in use google drive.
> 
> Got the fix. Needed to turn on shared drives in the admin console. Please follow https://support.google.com/a/answer/7337635

Thanks Gotanius that fixed my problem and I could continue with the installation.
I would like to add that my shared drives where on but I needed to allow users to create shared drives (this was off by default on the account)

To allow users to create shared drives, uncheck the Prevent users in your organization from creating new shared drives box.

**Comment by chazlarson** [comment]
Added documentation around this and some verification questions at the start of the run.
