### ISSUE TITLE
missing sa_file; is there supposed to be a combined version of all the other jsons?

### ISSUE THREAD

**Issue by SaintNick1214** [chazlarson/sb_gd#3]
config file requires sa_file but only accepts one file.  sa-gen creates some number of these jsons, i.e. 300.  If you point this config to a single one of those jsons, then I believe all mounts are using the same service account.

Is there a missing step where all the jsons are combined into one?

**Comment by chazlarson** [comment]
This single sa is used only for authenticating the remote; this is the same thing as going through `rclone config`, which asks for a single SA.  If you want to configure SARotate or something like that later to rotate SAs on the remote, that's a separate thing entirely.

in saltbox, there is work to do yet to change the default cloudplow config to use the set of SAs that are created.

**Comment by SaintNick1214** [comment]
Gotcha, I appreciate the explanation and validation of my findings.  I thought I was going crazy.

So It's easy for anyone who might look at this topic in the future, here is SArotate: https://github.com/saltydk/SARotate
