### ISSUE TITLE
Add capability to do encrypted team drives instead of unencrypted

### ISSUE THREAD

**Issue by SaintNick1214** [chazlarson/sb_gd#4]
Leaving more than 1PetaByte of content unencrypted on google drive is almost certainly going to cause your account to be discarded by google.  Encrypted drives protects against any automated scanners that might pick up on copywrited material etc.

I have already created this capability in my fork of this project under a branch called "encrypted-teamdrives".  It worked very well for me and I have verified that cloudplow uploads work as intended.  I do not consider myself a decent programmer so the code may be ugly or built in a way that can be improved.  Take a look and if you like what you see, create a new branch here and pull the code :)

**Comment by SaintNick1214** [comment]
note that my fork does not ask if you want the drives to be normal or encrypted, it just sets up encrypted drives with encrypted directories in them.  There's probably a better solution here, like merging the encrypted drive stuff into the main branch here with the ability to ask if you want encrypted drives or non-encrypted drives.

**Comment by chazlarson** [comment]
Saltbox isn't planning to add support for encrypted shared drives at this time, and given that this is intended as a temporary convenience script for saltbox installs, I don't see the point in including a feature that won't add anything for the target audience and could cause problems or drive a bunch more changes to saltbox.  The goal was to have a simple script that one can run without any more options than required in place of a wall of text describing how to set all this stuff up.
